[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "package name"
version = "version number"
authors = [
  {name = "your name"},
]
description = "your description"
requires-python = ">=3.7"
license = {text = "your license"}
keywords = ["keyword", "keyword2", "keyword3"]
